### ISSUE TITLE
brownout request - whitelisted package

### ISSUE THREAD

**Issue by jvanasco** [pypa/packaging-problems#133]
Would it be possible to provide a (temporary) whitelisted migration package to assist in upgrades, like offering pip by a name like 'pip-brownout' during this time?

I got locked out of pip for over an hour due to the brownout, then had to handle things manually. It's a bit of a pain distributing and installing a downloaded .tgz of pip onto Test and CI servers (multiple virtualenvs and the system version need to be installed).

Also as a suggestion: it would make sense to scatter the brownout window as some automated systems might not try to call pip/etc until the 2nd half of the hour.

**Comment by alex** [comment]
It shouldn't ever be the case that the brownout locks you out for an hour since it's only in affect the first N minutes of each hour.

Can you say more about what platform you're running on that hit this?

**Comment by jvanasco** [comment]
this was off a test machine at home: osx, python 2.7.13, pip 9.0.1
traffic was coming from NYC via spectrum.

**Comment by alex** [comment]
On macOS you should always be able to get a working pip by upgrading to pip 9.0.3, which can be done with https://bootstrap.pypa.io/get-pip.py at all times

**Comment by dstufft** [comment]
To be clear, if you're affected by the brownouts, you'll *also* be affected by load testing for the duration of the load test. Which is what happened here. Unfortunately it is not super clear when you're getting a failure due to load test vs brownout (other than by looking at the status page and determining if there is a load test underway).

**Comment by brainwane** [comment]
We are now [distributing the brownout window differently](https://status.python.org/incidents/hdx7w97m5hr8) -- see https://github.com/pypa/warehouse/issues/3411 .

I don't think we have any *load* tests scheduled this week, so this would be a good week to upgrade, I think.

@jvanasco were you able to get your environments upgraded?

**Comment by jvanasco** [comment]
@brainwane yes, thank you for asking. once I knew what was going on, I grabbed a tgz on my laptop and scp'd it where needed. i was just worried about how others with less experience would be able to deal with this, and those who missed the brownout windows.

**Comment by brainwane** [comment]
@jvanasco I [wrote and distributed an announcement](https://mail.python.org/pipermail/python-announce-list/2018-April/011885.html) that I hope helps. Thanks for sharing your experience and watching out for people who need more guidance; I agree that it would be good to give those folks more help.

I'm closing this issue because I think the right thing to do is to advise people to use `get-pip.py` -- as we're advising people, in [the PSF blog post](https://pyfound.blogspot.com/2018/03/warehouse-all-new-pypi-is-now-in-beta.html#Migrating) and in my python-announce-list announcement, which I also sent to [the pythonmac-sig list](https://mail.python.org/pipermail/pythonmac-sig/2018-April/024300.html). I do not know enough about where people who use Mac OS X get heads-ups about updates, so I'd appreciate any advice you could provide on that, and any help you could offer in getting the word out.
