### ISSUE TITLE
Pipenv / Requests: Can't `pipenv install` with fresh clone of Requests

### ISSUE THREAD

**Issue by brcrista** [pypa/packaging-problems#147]
(@brainwane asked me to write this, despite not being a well-formed issue)

During the PyCon sprint for Python packaging, @miriamsexton and I spent some time investigating Pipenv.  I remembered that the [Requests](https://github.com/requests/requests) library uses Pipenv.  We cloned the repo to play with Pipenv and see how it managed the Pipfile and lockfile.

These are the issues we encountered:
* `pipenv install` tries to sync the Pipfile.lock right away and fails:
![image](https://user-images.githubusercontent.com/33549821/40018455-5559ea86-578a-11e8-9edc-ab78008979d4.png)

* Same with `pipenv install --dev`
* `pipenv install --dev --skip-lock` succeeds, and I can `pipenv sync --dev` after that.  However, we get some bad hashes:
![image](https://user-images.githubusercontent.com/33549821/40018761-33116340-578b-11e8-90ae-a2f7b497fb2e.png)

* Trying to run `pipenv lock` yields this error:
![image](https://user-images.githubusercontent.com/33549821/40018802-5635b966-578b-11e8-9e12-96167a4ac0f6.png)

* What does Pipenv use the `host-environment-markers` in Pipfile.lock for?  We couldn't find any documentation on this.

We weren't sure if these issues are with Pipenv, the Pipfile / Pipfile.lock, or with our system environment.
* macOS High Sierra 10.13.3
* Anaconda Python 3.6.5 in PATH (from the screenshots, apparently the Pipenv commands were not using this interpeter)

**Comment by MiriamSexton** [comment]
Other things I noticed:

* I seemed to succe in installing with `pipenv install --ignore-pipfile`
<img width="547" alt="image" src="https://user-images.githubusercontent.com/700672/40019514-7140db08-578d-11e8-9b1d-810972bb5370.png">

* From my understanding it seems like `--ignore-pipfile` and `--skip-lock` are mutually exclusive and should be disallowed, but running`pipenv install --skip-lock --ignore-pipfile` seemed to work as well: 
<img width="627" alt="image" src="https://user-images.githubusercontent.com/700672/40019600-b270dea2-578d-11e8-8c74-0b1f24db204f.png">
If these are *not* mutually exclusive, the docs are not clear on the point.

**Comment by techalchemy** [comment]
Hey there @brcrista, I think you must be using an old version of pipenv -- we removed the host environment markers a few versions back (they were just metadata) 

As for the hash errors, it looks like the lockfile was generated with the pluggy sdist, and the pluggy maintianers uploaded a wheel sometime after that.  I double checked, and the sdist was uploaded on `2017-09-06T13:53:40` while the wheel was uploaded 7 months later on `2018-04-15T16:48:12`.  Pipenv, like pip, always prefers to install from wheels when available, but since the lockfile was generated when the wheel was not available, this is failing. I just opened a PR with requests to fix this: https://github.com/requests/requests/pull/4646

`--ignore-pipfile` and `--skip-lock` may not be _enforced_ as mutually exclusive -- if you pass in `--skip-lock` I believe the current behavior is that it always will use the pipfile since otherwise there is nothing pipenv can ever do.  Not sure that is actually desirable, I don't think anyone planned for it.  I currently feel they should be mutually exclusive, but if you file an issue we can discuss further

The issue you ran into with egg installs was related to a resolver bug we fixed (I think it's fixed, anyway -- we haven't had many reports on it since we rolled the fix).

Hopefully this helps, but let me know if you have anymore questions

**Comment by nateprewitt** [comment]
Hey @techalchemy, thanks for sending over the PR. The lockfile in Requests master branch has been broken due to a resolution conflict for a few months. I think I've got everything working now and will push up a new Pipfile.lock tomorrow once we get a build fix merged.

@brcrista Sorry for the inconvenience. You should be able to clone sometime tomorrow afternoon and have the issues resolved.

**Comment by brcrista** [comment]
Thanks!  I was just bashing on this, so no inconvenience.  I'll give it another try and see if it works.

I'm still confused about the `--ignore-pipfile` setting.  If bare `pipenv install` uses Pipfile.lock (which I would say is the sensible default), doesn't the Pipfile.lock alone completely specify all the dependencies?

I guess I don't understand what the Pipfile would add here.  My understanding is that the Pipfile is a human-readable record of your direct dependencies, while Pipfile.lock is a complete, machine-readable record of all your dependencies and transitive dependencies, with version constraints.

**Comment by nateprewitt** [comment]
@brcrista, take the case where you’re adding a bunch of packages to your Pipfile to test things out but don’t necessarily want your Pipfile.lock updating while you’re testing. You can use `pipenv install x y z --skip-lock` to do this.

Now you’ve got a case where your Pipfile and Pipfile.lock are no longer in sync. You may want to go back to the old state, which is still stored in the lockfile. In order to avoid being prompted to relock from the new Pipfile, you can explicitly say “I know I’m in an inconsistent state, just install the lock”. It’s not a super common feature but has a use case during development.

**Comment by brcrista** [comment]
Thanks @techalchemy and @nateprewitt !  I can confirm `pipenv install --dev` succeeds for me now on a clean project.  I'll close this issue.
