### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by kentaro0919** [pypa/packaging-problems#151]
Is there some typo?

error with
```
$python setup.py sdist bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
```
run with

```
$ python setup.py sdist
running sdist
running egg_info
creating tokima.egg-info
writing tokima.egg-info/PKG-INFO
writing top-level names to tokima.egg-info/top_level.txt
writing dependency_links to tokima.egg-info/dependency_links.txt
writing manifest file 'tokima.egg-info/SOURCES.txt'
reading manifest file 'tokima.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'tokima.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt

running check
creating tokima-0.0.1
creating tokima-0.0.1/tokima.egg-info
making hard links in tokima-0.0.1...
hard linking MANIFEST.in -> tokima-0.0.1
hard linking setup.cfg -> tokima-0.0.1
hard linking setup.py -> tokima-0.0.1
hard linking tokima.egg-info/PKG-INFO -> tokima-0.0.1/tokima.egg-info
hard linking tokima.egg-info/SOURCES.txt -> tokima-0.0.1/tokima.egg-info
hard linking tokima.egg-info/dependency_links.txt -> tokima-0.0.1/tokima.egg-info
hard linking tokima.egg-info/top_level.txt -> tokima-0.0.1/tokima.egg-info
copying setup.cfg -> tokima-0.0.1
Writing tokima-0.0.1/setup.cfg
creating dist
Creating tar archive
removing 'tokima-0.0.1' (and everything under it)
```

**Comment by theacodes** [comment]
Hey @kentaro0919, can you confirm that `wheel` is installed? You can install it using:

```
python3 -m pip install --user --upgrade setuptools wheel
```

Then make sure you run `setup.py` using the *same* interpreter if you have multiple ones, so:

```
python3 setup.py sdist bdist_wheel
```

**Comment by kentaro0919** [comment]
After running 

```sh
$pip install -U wheel
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/81/30/e935244ca6165187ae8be876b6316ae201b71485538ffac1d718843025a9/wheel-0.31.1-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.31.1
```

I was able to run as in the tutorial

```
$python setup.py sdist bdist_wheel
running sdist
running egg_info
creating tokima.egg-info
writing tokima.egg-info/PKG-INFO
writing dependency_links to tokima.egg-info/dependency_links.txt
writing top-level names to tokima.egg-info/top_level.txt
writing manifest file 'tokima.egg-info/SOURCES.txt'
reading manifest file 'tokima.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'tokima.egg-info/SOURCES.txt'
running check
creating tokima-0.0.1
creating tokima-0.0.1/tokima.egg-info
copying files to tokima-0.0.1...
copying MANIFEST.in -> tokima-0.0.1
copying README.md -> tokima-0.0.1
copying setup.cfg -> tokima-0.0.1
copying setup.py -> tokima-0.0.1
copying tokima.egg-info/PKG-INFO -> tokima-0.0.1/tokima.egg-info
copying tokima.egg-info/SOURCES.txt -> tokima-0.0.1/tokima.egg-info
copying tokima.egg-info/dependency_links.txt -> tokima-0.0.1/tokima.egg-info
copying tokima.egg-info/top_level.txt -> tokima-0.0.1/tokima.egg-info
Writing tokima-0.0.1/setup.cfg
creating dist
Creating tar archive
removing 'tokima-0.0.1' (and everything under it)
running bdist_wheel
running build
installing to build/bdist.macosx-10.13-x86_64/wheel
running install
running install_egg_info
Copying tokima.egg-info to build/bdist.macosx-10.13-x86_64/wheel/tokima-0.0.1-py3.6.egg-info
running install_scripts
creating build/bdist.macosx-10.13-x86_64/wheel/tokima-0.0.1.dist-info/WHEEL
creating '/Users/cdn-104/Desktop/tokima/dist/tokima-0.0.1-py3-none-any.whl' and adding '.' to it
adding 'tokima-0.0.1.dist-info/top_level.txt'
adding 'tokima-0.0.1.dist-info/WHEEL'
adding 'tokima-0.0.1.dist-info/METADATA'
adding 'tokima-0.0.1.dist-info/RECORD'
removing build/bdist.macosx-10.13-x86_64/wheel
```

**Comment by theacodes** [comment]
Good to hear. :)

**Comment by fnunnari** [comment]
Still, I think that the tutorial should be updated to help users using a venv.
**When using a virtual environment**, the command:

```
python3 -m pip install --user --upgrade setuptools wheel
```

should be invoked **without** the --user option:

```
python3 -m pip install --upgrade setuptools wheel
```

**Comment by gaborbernat** [comment]
A more appropriate and current best practice solution I believe would be to move to ``pyproject.toml`` and invoke via ``pep517.build``. That would mean the guide would be flit/poetry compatible.

**Comment by merwok** [comment]
Doesn’t it seem kind of low-level to call `-m pep517.build`?

If I chose flit to maintain a lib, my interface is `flit build` and it’s all right.
Another project using setuptools needs `./setup.py bdist_wheel` as it always has.

IOW I feel that PEP 517 is in the domain of pluggable backends for installers, not developer tools to package and distribute libs.

**Comment by gaborbernat** [comment]
Calling ``setup.py bdist_wheel`` is a lot lower level and not guaranteed to work (as at call time build dependencies are not guaranteed to be present). Calling pep517.build is totally fine until pip gets a build command. Similarly with flit build. The only sane way to build packages guaranteed not to fail because of a bad build frontend is with ``pep517.build``.

**Comment by merwok** [comment]
Let me use other terms to explain my perceptions :)

Calling `python -m pep517.build` feels like I’m calling something internal.
(As a command-line person, `python -m` will probably never feel natural to me.  I want scripts!)

`./setup.py bdist_wheel` is lower level than a pip command: exactly! because what I’m doing is one task, just package one lib.  I am not thinking about pip and installation/integration at that moment, I don’t need dependency resolution, downloads from PyPI, etc.

Yes, I need build dependencies, but if I’m developing a lib I am in a working development virtualenv.  `flit build` feels like exactly what I need; pip is unconnected.

**Comment by pganssle** [comment]
> Calling python -m pep517.build feels like I’m calling something internal.
(As a command-line person, python -m will probably never feel natural to me. I want scripts!)

`pep517.build` is explicitly created as an entry-point for end users.

> ./setup.py bdist_wheel is lower level than a pip command: exactly! because what I’m doing is one task, just package one lib. I am not thinking about pip and installation/integration at that moment, I don’t need dependency resolution, downloads from PyPI, etc.

I would argue that `setup.py bdist_wheel` or `setup.py sdist` are *especially* bad when building something you intend to distribute, because `pep517.build` creates an isolated, reproducible environment, whereas direct invocations of `setup.py` just use whatever environment you happen to have configured.

I personally don't like the idea of `pip` becoming a build tool, and prefer a dedicated build frontend, but I realize the scope of `pip` is still up for discussion.

**Comment by gaborbernat** [comment]
This is historical but let's say ``python -m`` is the sane way of calling things, as it's guaranteed to work on all platforms (requires less path mangling). 

``./setup.py bdist_wheel`` - well what you actually want is to build a wheel (which is a high-level command, not a low level generate this info, I've already setup the inner things) -> this is guaranteed to work correctly by calling that low-level command and often produces cryptic errors confusing new users. Users should interact with the high-level concepts, not the low-level tool specific one. The low level is there for tools, high-level cli tools for users.

> Yes, I need build dependencies, but if I’m developing a lib I am in a working development virtualenv.

Build dependencies have nothing to do with runtime dependencies. The fact that you have a development virtualenv does not guarantee you have correct build dependencies.
