### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by sithlord1234** [pypa/packaging-problems#155]
HTTPError: 404 Client Error: Not Found for url: https://pypi.org/legacy/

**Comment by ncoghlan** [comment]
@sithlord1234 Which step in the guide were you working on when you hit that, and which tool emitted it?

(There genuinely isn't a page at that URL - the API endpoint for production uploads is at https://upload.python.org/legacy/, while the test one is https://test.python.org/legacy/)

(I did file https://github.com/pypa/warehouse/issues/4087 though, since the latter isn't showing the expected API endpoint notification page)

**Comment by pradyunsg** [comment]
Can we close this due to a lack of a response?
