### ISSUE TITLE
Unable to manage a project removed from Pypi

### ISSUE THREAD

**Issue by dadadel** [pypa/packaging-problems#180]
A *Pyment* project was create once on Pypi before being removed and the ownership transferred to the user [asettouf](https://pypi.org/user/asettouf/). 
As related in [this issue](https://github.com/dadadel/pyment/issues/37), @asettouf can see *Pyment* in his Pypi project but cannot manage it in order to transfer the ownship to my Pypi user [dadel](https://pypi.org/user/dadel/).
Is there a particular way to address this problem ?

**Comment by ewdurbin** [comment]
Hello @dadadel!

I can confirm that user `asettouf` was added as a Maintainer to the project on 2017-11-16.

PyPI has two roles for collaborators on projects, Owner and Maintainer. 

* Maintainer: Can upload releases for a package. Cannot add collaborators. Cannot delete files, releases, or the project.
* Owner: Can upload releases. Can add other collaborators. Can delete files, releases, or the entire project.

The easiest path forward is to have the user `meyt`, who is currently the sole Owner of the project update `asettouf`'s role to "Owner" so that they can fully manage the project and transfer ownership.

**Comment by dadadel** [comment]
@ewdurbin,
Thanks for your reply, I will ask meyt for granting me the owner role.
