### ISSUE TITLE
pypi upload issue for bioconvert claiming existence of previous existing version

### ISSUE THREAD

**Issue by cokelaer** [pypa/packaging-problems#189]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Linux fedora fc23

2. What is your Python version?

3.5.2

3. What version of pip do you have?

10.0.1

4. Could you describe your issue in as much detail as possible?

I have a package called bioconvert that we upload the first time on the 12th of Oct 2017.
Since then, we have created releases starting at 0.0.1 then 0.0.2 and so on (https://libraries.io/pypi/bioconvert/versions). We are now at 0.1.13 and I wanted to upload version 0.1.14 today with

    python setup.py sdist upload 

as usual but got this error:

    Upload failed (400): This filename has already been used, use a different version. See https://pypi.org/help/#file-name-reuse

Looking at https://libraries.io/pypi/bioconvert/versions there is indeed a version 0.1.14 that was already published but ... in 2013 !?!? and there is also version 1.0.0 in 2014 that is 3-4 years before we registered the software ? 

Is it possible that the software was created 3-4 years ago then deleted and that the history of that older/deleted software clashes with our registration ?any ideas ? thanks in advance

**Comment by ewdurbin** [comment]
Hello @cokelaer. After checking the Journals for bioconvert, I see that this Project name was originally registered `2012-12-03 16:39:15` by `cokelaer`, and later removed on `2015-06-15 20:57:01` by `cokelaer`. The current Project was created `2017-10-12 15:03:52.566576` by `cokelaer`. You should be able to view this same history at https://pypi.org/manage/project/bioconvert/history/


During that time, releases were created for versions `0.1.0`, `0.1.1`, `0.1.2`, `0.1.3`, `0.1.4`, and `1.0.0`. `0.1.4` and `1.0.0` were created after PyPI hosting modes were changed and 
 began tracking filenames uploaded, which is why they are not available for reuse, but the earlier file names were.

Per https://pypi.org/help/#file-name-reuse, the filenames `bioconvert-0.1.4.tar.gz` and `bioconvert-1.0.0.tar.gz` will not be available for reuse in the new re-registered Project for `bioconvert`.

**Comment by cokelaer** [comment]
I guess there will be no solution given the policy described in the links you provided. I'm closing this issue. 
thanks for the feedback.

**Comment by ewdurbin** [comment]
There is technically a work around that exists, by uploading a `.zip` sdist rather than a `.tar.gz` sdist.

**Comment by cokelaer** [comment]
thanks for the **.zip** tip
