### ISSUE TITLE
Request for package size increase for tf-nightly-xla-gpu

### ISSUE THREAD

**Issue by annarev** [pypa/packaging-problems#191]
4. Could you describe your issue in as much detail as possible?

Latest tf-nightly-xla-gpu package size is 262M and our current limit is 260M. Is it possible to increase our package size limit to 300M?

Thank you,
Anna

**Comment by ewdurbin** [comment]
@annarev, is it possible that a maintainer of the `tf-nightly-xla-gpu` project could go back and remove older nightlies after some time period? projects with large file size limits are a burden for downstream mirrors of PyPI. You can see that this project is already in the top 100 projects in overall size on PyPI at https://pypi.org/stats/.

For now I've updated the limit to 275M so that we can touch base again if the project exceeds that size.

**Comment by annarev** [comment]
Thank you! I just deleted everything except 2 most recent nightlies.
