### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by tmdd** [pypa/packaging-problems#228]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

<win10>

2. What is your Python version?

<3.6.4>

3. What version of pip do you have?

<pip 18.0>!

4. Could you describe your issue in as much detail as possible?

<when I Generate distribution archives, The result suggests that 'python3' is not an internal or external command, nor is it a runnable program.Then I use "python setup.py sdist bdist_wheel", I get the message: "Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg), usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help">

**Comment by merwok** [comment]
Please answer the OS question :)   If you are on windows, this may help for the «command not found» error: https://docs.python.org/3/using/windows.html

The «unknown option» may be caused by a missing setuptools or an old version.
https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi

**Comment by kirankotari** [comment]
By looking I can say system couldn't find python3. 

if you are in windows with only python 3+ installed then use `python` instead of `python3`

if you are having multiple python's installed then check the path variable does it contains python3 
   for more details follow the below link: 
   https://datascience.com.co/how-to-install-python-2-7-and-3-6-in-windows-10-add-python-path-281e7eae62a
