### ISSUE TITLE
Packaging Python Projects tutorial is confusing when used as a template

### ISSUE THREAD

**Issue by alchemyst** [pypa/packaging-problems#246]
I packaged up an existing project today and was confused by a part of the Packaging Python Projects tutorial which was introduced by [#592](https://github.com/pypa/python-packaging-user-guide/pull/592) (appending your username to the package name). It wasn't clear to me at the time that I couldn't use these instructions as a scaffold to package up my own project.

 [#592](https://github.com/pypa/python-packaging-user-guide/pull/592) was a reaction to [the problem](https://github.com/pypa/python-packaging-user-guide/issues/584) that following the instructions verbatim, effectively creating a new package called `example_pkg` and then trying to upload it with that name would result in a collision. I understand that use case, but I was attempting to use this as a "walkthrough" for packaging my own project, just substituting `my_project_name` for `example_pkg` everywhere. I had done the same thing before on other projects which I helped package and it worked fine then. Particularly, I know things have changed on pypi lately and thought that appending my username was now a requirement of the packaging process, so I dutifully appended it wherever the tutorial did. 

I think the most confusing part was that the end of the tutorial says "If you want to upload your package to the real Python Package Index you can do it by registering an account on https://pypi.org and following the same instructions, however, use `twine upload dist/*` to upload your package and enter your credentials for the account you registered on the real PyPI. You can install your package from the real PyPI using `pip install [your-package]`." It didn't mention that the username thing was just for this particular tutorial.

I'm not sure what the best way is to avoid this. I personally think most users will be starting with code which already exists and wanting to know what to add to actually get it on to PyPI and so will be looking for guidance about how to do that. Perhaps just a page with links to "I have code already, show me instructions on how to package the existing code" and "I would like to start a new project from scratch" would make this easier?

**Comment by theacodes** [comment]
Unfortunately, I don't think we're even able to provide a "add these files to your project and you're good"-type tutorial. There's just.... too many possibilities. I think the best route here is:

1. Amend the tutorial to explicitly mention what it does, something like "This tutorial walks you through publishing a simple example project. If you already have a project that you want to package, we strongly recommend you go through this process the first time with the provided example package instead of your own. Once you've gone through this tutorial you'll have a good grasp of the tools and processes, which will help you when packaging your own project."
2. Add a note that appending your username isn't a strict requirement of PyPI, it's just there to avoid name collisions.

@di, can you move this to pypa/pypa/python-packaging-user-guide? (Apparently I don't have the rights needed to do that)

**Comment by alchemyst** [comment]
I appreciate that we can't have a one-size-fits-all single page solution, but I would be willing to spend some time myself building something like a "built-your-own-adventure" version (or is the more contemporary reference a Bandersnatch version?). Something like

1. Do you currently have all your code in just one file which runs your analysis? Go to 2. Else go to 3
2. Add a if __name__ block or separate your functions/classes and actual code. Now go to 3
3. Do you have your modules in one root folder? Go to 4 else go to 5
4. Move your module files to a package folder, add an `__init__.py` file.
5. Do you have your modules in a package (a directory with an `__init__.py`). Add a config.py file to your root directory and go to 5 (some side steps here about licensing etc)

I feel this covers most of the more common entry points for people starting without code. There may be some people who are starting from nothing and wanting to get hello world onto PyPI but these people are well serviced by just downloading the sample project rather than actually following the steps, I think.

**Comment by theacodes** [comment]
> I would be willing to spend some time myself building something like a "built-your-own-adventure" version

You are more than welcome to do so, but I'm not sure if the packaging.python.org docs are the appropriate place. I'd certainly be willing to consider where to put it, and help you find an alternative place if necessary. I believe there's a lot of learning styles and approaches, but we have to be cautious of what we put into a single docset, as too many slightly different versions of the same tutorial causes more issues than it solves.

> There may be some people who are starting from nothing and wanting to get hello world onto PyPI but these people are well serviced by just downloading the sample project rather than actually following the steps, I think.

Completely disagree. User studies show that more people were more successful with learning the concepts and being able to successfully retain them when they walk through a tutorial that involves them *creating* something (even if it is just copy/paste) rather than just downloading existing code and running commands against it.

**Comment by alchemyst** [comment]
The references to teaching in your response has made me see this tutorial page in a whole new light. I think I was just approaching it from a very utilitarian point of view, imagining the goal was to minimise the time taken to get a package onto PyPI. If your objective is to have an activity that teaches a person about how all these steps work, the page is pretty good as is. I am a lecturer myself so I appreciate the effort into teaching.

I now fully agree with your suggestions above in terms of clarifying throughout the process that the username thing is only for this particular tutorial and not a general rule for packages on PyPI. I would also recommend adding a similar disclaimer for the `name =` part in `__init__.py` and rewording the last bit under next steps to indicate what should be left out.

Thanks for engaging on this. I appreciate the effort and now also understand the goals a bit better.

**Comment by theacodes** [comment]
Awesome. Once I find some time I'll work on adding those items to the tutorial (or if someone else wants to do it, I'm happy to review).

**Comment by alchemyst** [comment]
I've created a [PR](https://github.com/pypa/packaging.python.org/pull/602) for this.
