### ISSUE TITLE
lxml 4.3.4 homepage on pipy.org is hijacked - redirects to political site

### ISSUE THREAD

**Issue by tamasoz** [pypa/packaging-problems#273]
The homepage shown for the lxml python lib  on the https://pypi.org/project/lxml/ redirects to some political site. Thankfully no one looked at my screen at work when I naively opened the library homepage via pypi.org...

Can you rectify this issue please?

Thanks

**Comment by brainwane** [comment]
Hi @tamasoz. Thanks for your note. I transferred the issue because this is more about packaging and PyPI in general than about the PyPA website.

For others who want more context on this issue: I see that https://pypi.org/project/lxml/ mentions http://lxml.de/ as its homepage, and that right now lxml.de is redirecting to https://www.fridaysforfuture.org/ , a website organizing climate change protests. [The Wayback Machine](https://web.archive.org/web/*/lxml.de) demonstrates that this redirect started this year.

I see from the [lxml mailing list](https://mailman-mail5.webfaction.com/pipermail/lxml/2019-April/024039.html) that [project lead Stefan Behnel](http://consulting.behnel.de/#lxml) decided to start this redirect. So it's not a hijack. If you'd like to talk with him about that decision, I suggest you follow up on that mailing list thread.

Hope this helps, and best wishes!
