### ISSUE TITLE
Needing to specify every package in packages is tedious and error prone

### ISSUE THREAD

**Issue by dstufft** [pypa/packaging-problems#28]
A major gripe is the packages=[] entry. They simply want it to point it at a directory, walk it, try to import it and there you have your packages. Instead they need to explicitly specify what packages I have and every module that's part of it. This should be auto-discoverable once you have the 'root' package but they've never been able to get something like that work.

setuptools has it's find_packages feature but that won't work with distutils. In general I think specifying what goes _into_ a package can be made better.

**Comment by ncoghlan** [comment]
With package consumption decoupled from the choice of publishing toolchain, folks are now free to opt for alternatives like `flit`, which take very different approaches to specify distribution package contents from those offered by `setuptools`/`distutils`.

As such, that UX is now a matter to be considered for the specific publishing tools, rather than an ecosystem level concern.
