### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by afialvi** [pypa/packaging-problems#283]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
MacOS 10.14.3

2. What is your Python version?
python 3.6

3. What version of pip do you have?
Pip 19.2.2

4. Could you describe your issue in as much detail as possible?
Here's my issue on stack overflow:
https://stackoverflow.com/questions/57574354/how-to-check-whl-file-correctly-generated
It gives import error after installing my generated wheel. Please check

**Comment by merwok** [comment]
The linked question has an answer.  The problem here is a misunderstanding of modules and scripts (also of the project layout vs. python import layout, there is an unneeded `__init__.py` file in repo root).  @afialvi could you say what doc you read that wasn’t clear enough to let you avoid the misunderstanding?
