### ISSUE TITLE
Trouble following packpi@raspbrerrypi:~/kingcobra$ python3 setup.py sdist bdist_wheel Traceback (most recent call last):   File "setup.py", line 5, in <module>     setuptools.setup( NameError: name 'setuptools' is not defined pi@raspbrerrypi:~/kingcobra$ cd pi@raspbrerrypi:~$ dist/ bash: dist/: No such file or directory pi@raspbrerrypi:~$   kingcobra_srinivasanp-0.0.1-py3-none-any.whl bash: kingcobra_srinivasanp-0.0.1-py3-none-any.whl: command not foundaging libraries tutorial

### ISSUE THREAD

**Issue by srini-pro** [pypa/packaging-problems#419]

**Comment by merwok** [comment]
Hello!  Seems that you put your error message in the issue title instead of the description, and that you deleted all the questions too!  You can edit that at any time.

The key here is to pay attention to the error message:

> NameError: name 'setuptools' is not defined 

that means you probably have `setuptools.setup(...)` but you forgot `import setuptools` first.

**Comment by srini-pro** [comment]
thankyou very much

**Comment by merwok** [comment]
Ok you can close this ticket then!
