### ISSUE TITLE
Twine upload is fine but after installing the package it dosent imports

### ISSUE THREAD

**Issue by Saad-py** [pypa/packaging-problems#429]
I used twine upload to upload a simple package called addlol, I followed this tutorial https://www.freecodecamp.org/news/build-your-first-python-package/

I did everything they said my files are same to them but after doing pip install addlol it installs it in sitepackages and when I tied to test it, it dosen't imports

Kidly Help Me

**Comment by bhrutledge** [comment]
Since this is not an issue with Twine, I transferred it to a more appropriate project for getting help with packaging.

**Comment by merwok** [comment]
Hello!  Please give more info in bug reports so that people can make hypotheses to help you 🙂 
For example, showing what your project looks like (screenshot with all project files), and most importantly copy-pasting the whole error message.

I checked the `addlol` package on PyPI.  It installs a package called `extras`, with a submodule `extras.divide`.  The `__init__` file uses the debatable idiom of automatically importing from sub-packages, but does it using an implicit relative import, which I think is deprecated since Python 2.5.  This should work: `from .divide import dev`.  Please try it and tell us if it helped!  If I didn’t understand the problem correctly, please copy-paste what you’re doing `import something` and the error message.

I would recommend not doing that: sub-modules are not auto-imported by all projects, so it’s fine if people need to do `import extras.divide` or `import extras.multiply` to access specific functions of your package.

**Comment by bhrutledge** [comment]
Looking at the contents of the packages downloaded from https://pypi.org/project/addlol/#files:

```
$ tar tzvf addlol-0.0.1.tar.gz 
drwxrwxrwx  0 0      0           0 Jan 17 00:58 addlol-0.0.1/
-rw-rw-rw-  0 0      0         577 Jan 17 00:58 addlol-0.0.1/PKG-INFO
drwxrwxrwx  0 0      0           0 Jan 17 00:58 addlol-0.0.1/addlol.egg-info/
-rw-rw-rw-  0 0      0         577 Jan 17 00:58 addlol-0.0.1/addlol.egg-info/PKG-INFO
-rw-rw-rw-  0 0      0         164 Jan 17 00:58 addlol-0.0.1/addlol.egg-info/SOURCES.txt
-rw-rw-rw-  0 0      0           1 Jan 17 00:58 addlol-0.0.1/addlol.egg-info/dependency_links.txt
-rw-rw-rw-  0 0      0           7 Jan 17 00:58 addlol-0.0.1/addlol.egg-info/top_level.txt
drwxrwxrwx  0 0      0           0 Jan 17 00:58 addlol-0.0.1/extras/
-rw-rw-rw-  0 0      0          20 Jan 17 00:49 addlol-0.0.1/extras/__init__.py
-rw-rw-rw-  0 0      0          27 Jan 17 00:48 addlol-0.0.1/extras/divide.py
-rw-rw-rw-  0 0      0          42 Jan 17 00:58 addlol-0.0.1/setup.cfg
-rw-rw-rw-  0 0      0        1013 Jan 17 00:58 addlol-0.0.1/setup.py

$ unzip -l addlol-0.0.1-py3-none-any.whl  
Archive:  addlol-0.0.1-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
       20  01-17-2021 05:49   extras/__init__.py
       27  01-17-2021 05:48   extras/divide.py
      550  01-17-2021 05:58   addlol-0.0.1.dist-info/METADATA
       92  01-17-2021 05:58   addlol-0.0.1.dist-info/WHEEL
        7  01-17-2021 05:58   addlol-0.0.1.dist-info/top_level.txt
      436  01-17-2021 05:58   addlol-0.0.1.dist-info/RECORD
---------                     -------
     1132                     6 files
```

I note that there isn't an `addlol` directory, or an `addlol.py`, which is why `import addlol` would fail.

I'm _guessing_ your source directory is something like this:

```
addlol
├── extras
│   ├── __init__.py
│   └── divide.py
├── setup.cfg
└── setup.py
```

I think it should be something more like this:

```
addlol
├── addlol
│   ├── __init__.py
│   └── extras
│       ├── __init__.py
│       └── divide.py
├── setup.cfg
└── setup.py
```

The nested `addlol` directory might seem redundant, but that's actually the [package directory](https://packaging.python.org/glossary/#term-Import-Package) that's the basis for importing.

[Twine](https://github.com/pypa/twine) (and many other projects) follows a similar structure:

```
twine
├── twine
│   ├── __init__.py
│   └── commands
│       ├── __init__.py
│       └── upload.py
├── setup.cfg
└── setup.py
```

The root directory in this tree is commonly the name of the GitHub repository, and is frequently the same as the package directory. However, it doesn't have to be, and it has no impact on `twine upload` or `pip install`.

Also, while the tutorial you linked seems decent, there's a more complete one at https://packaging.python.org/tutorials/packaging-projects/.

**Comment by Saad-py** [comment]
@merwok 

I tried doing 
`from extras import multiply`
`from extras.multiply import mul`

BUT IT RESULTED  in an error no module found.

**Comment by Saad-py** [comment]
@bhrutledge 
My dir looks like


 addlol
---------__init__.py
---------setup.py
---------add.py
---------subtract.py 
 --------extras
---------------__init__.py
---------------divide.py
---------------multiply.py

Extras is like a sub dir

Kindly tell me any tutorial for makin the package an uploading it using twine

OR  if i try something like 
Base folder
----------base dir
------------------main.py 
------------------__init__.py
------------------setup.py

Will it work 
cause I tried tens of times still I wasn't able to import anything and if youopen my account in ypi.org you can see many modules there and that is all a test I have to upload my main lib.
After doing a test

**Comment by Saad-py** [comment]
And Thank you very much to both of you for replying or many people in github just ignore problem until they are not haaving it

**Comment by Saad-py** [comment]
And I will create anothr test named memearithmetic and I will make the dir somewhat near 
addlol
├── addlol
│   ├── __init__.py
│   └── extras
│       ├── __init__.py
│       └── divide.py
├── setup.cfg
└── setup.py


And what is a .cfg file
I am a an intermediate not an expert, after all I am just 13 yrs

**Comment by Saad-py** [comment]
So can I delete addlol

**Comment by Saad-py** [comment]
And make another test

**Comment by Saad-py** [comment]
![image](https://user-images.githubusercontent.com/73306005/104879457-4fd0db00-5977-11eb-8eea-32a5c49ec8fe.png)


So this is ho my directory looks like and I am going to build the wheel and upload it using twine

**Comment by Saad-py** [comment]
YAY Thanks You both its good now
I created something called memearith 
just pip install memearith 
and then import meme 
then meme has add the  meme.extra.div.div 


Down Is a screenshot for the tests I did
![image](https://user-images.githubusercontent.com/73306005/104880219-9c68e600-5978-11eb-98b7-523c094f785b.png)


Thanks AGAIN @merwok  and @bhrutledge

**Comment by bhrutledge** [comment]
@Saad-py I'm glad you were able to figure it out. 

The `setup.cfg` file is an alternative to `setup.py`, using a declarative syntax instead of executable Python code. For an example, see Twine's:

- https://github.com/pypa/twine/blob/master/setup.cfg
- https://github.com/pypa/twine/blob/master/setup.py

There's not as much documentation about using `setup.cfg` as one might like, but it's getting better. If you're curious, take a look at https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html.

Also, a bit of GitHub advice: detailed comments of what you tried and what did and didn't work are great, but I would take some time to compose them into one larger comment, instead of many small ones. It will make it easier for other people to read and respond to them.

**Comment by Saad-py** [comment]
Hey guys I shouldn't have reopened this issue but do you know an article or somewhere where I can find more about the setup.py list thing as i want to also add a logo and some external links

**Comment by merwok** [comment]
Yes sure this is the official website with many resources: https://packaging.python.org/guides/distributing-packages-using-setuptools/

I don’t know what you mean with _adding a logo_ so I don’t have a link for that.

For questions that are not strictly problems, please use this forum rather than bug reports: https://discuss.python.org/c/users/7

**Comment by bhrutledge** [comment]
Also, you can still comment on closed issues, unless they have been locked. With that in mind, I'm closing this one.

**Comment by Saad-py** [comment]
I have the same problem again

**Comment by merwok** [comment]
We can’t help without information.  Show us your file layout, your packaging config file, the commands you type, the error message you get.

**Comment by henryiii** [comment]
Setup.cfg is now used in the basic example at https://packaging.python.org/tutorials/packaging-projects/ if that helps.

**Comment by Saad-py** [comment]
Overview of the folder:
after building wheel
![image](https://user-images.githubusercontent.com/73306005/111021037-2c5c6680-83e3-11eb-9fac-17d559562601.png)

**Comment by henryiii** [comment]
What's in your setup.py and what's in your dist folder?

**Comment by Saad-py** [comment]
My setup.py:

```
import setuptools as set

set.setup(
    name = "Neux",
    version = "1.0.0",
    author = "Saad-py",
    author_email = "saadyarkhan11@gmail.com",
    description="again somethings ",
    long_description="somethings",
)
```

Inside dist direcotry

![image](https://user-images.githubusercontent.com/73306005/111034539-a1ee2400-842f-11eb-919d-f9c866604b2b.png)

**Comment by bhrutledge** [comment]
I downloaded the files you uploaded from https://pypi.org/project/Neux/#files. It looks like you're missing the source directory:

```
$ tar tzvf Neux-1.0.0.tar.gz 
drwxrwxrwx  0 0      0           0 Mar 12 04:22 Neux-1.0.0/
drwxrwxrwx  0 0      0           0 Mar 12 04:22 Neux-1.0.0/Neux.egg-info/
-rw-rw-rw-  0 0      0        1038 Mar 12 04:22 Neux-1.0.0/Neux.egg-info/PKG-INFO
-rw-rw-rw-  0 0      0         120 Mar 12 04:22 Neux-1.0.0/Neux.egg-info/SOURCES.txt
-rw-rw-rw-  0 0      0           1 Mar 12 04:22 Neux-1.0.0/Neux.egg-info/dependency_links.txt
-rw-rw-rw-  0 0      0           1 Mar 12 04:22 Neux-1.0.0/Neux.egg-info/top_level.txt
-rw-rw-rw-  0 0      0        1038 Mar 12 04:22 Neux-1.0.0/PKG-INFO
-rw-rw-rw-  0 0      0          42 Mar 12 04:22 Neux-1.0.0/setup.cfg
-rw-rw-rw-  0 0      0         944 Mar 12 04:17 Neux-1.0.0/setup.py

$ tar tzvf Neux-1.0.0-py3-none-any.whl
-rw-rw-r--  0 0      0         891 Mar 12 09:22 Neux-1.0.0.dist-info/METADATA
-rw-rw-r--  0 0      0          92 Mar 12 09:22 Neux-1.0.0.dist-info/WHEEL
-rw-rw-r--  0 0      0           1 Mar 12 09:22 Neux-1.0.0.dist-info/top_level.txt
-rw-rw-r--  0 0      0         284 Mar 12 09:22 Neux-1.0.0.dist-info/RECORD
```

I think you need `find_packages` in your `setup()` call, e.g.:

```python
from setuptools import setup, find_packages

setup(
    name="Neux",
    version="1.0.0",
    author="Saad-py",
    author_email="saadyarkhan11@gmail.com",
    description="again somethings ",
    long_description="somethings",
    packages=find_packages(),
)
```

That said, I suggest working through the [Python Packaging Tutorial](https://packaging.python.org/tutorials/packaging-projects/), which demonstrates a more current approach using `setup.cfg` instead of `setup.py`.

**Comment by Saad-py** [comment]
What source dirctory are you talking about

**Comment by layday** [comment]
The directory containing the code for your package.  You need to tell `setup` where your code is located so that it's able to package it.

**Comment by Saad-py** [comment]
> The directory containing the code for your package. You need to tell `setup` where your code is located so that it's able to package it.

How do I do that in setup.py

**Comment by layday** [comment]
You need to add `packages=find_packages()` to `setup`, like @bhrutledge has shown above.

**Comment by bhrutledge** [comment]
Building on [my previous comment](https://github.com/pypa/packaging-problems/issues/429#issuecomment-798515953), it looks like your [distribution package](https://packaging.python.org/glossary/#term-Distribution-Package) files (the `.tar.gz` and `.whl` files) are missing the [import package](https://packaging.python.org/glossary/#term-Import-Package) directory that contains your source code. Looking at your [screenshot](https://github.com/pypa/packaging-problems/issues/429#issuecomment-797874143), I'm guessing that's the "Nexus" directory.

Adding the `packages=find_packages()` will tell the `setup()` function to look for import packages in the current directory, and add them to the distribution package.

**Comment by Saad-py** [comment]
ok I will try

**Comment by Saad-py** [comment]
Nope that is also not working
testfoRnExuDSA is the test I created but no HOPE :(

**Comment by merwok** [comment]
What are your python modules (files with py extension or directories containing `__init__.py`)?
What is inside your setup script or config file?
Please understand that it’s impossible to help without you telling exactly what you have and what you’re doing.

**Comment by Saad-py** [comment]
Oh My God,
The most annoying thing happened, after installing the test lib and trying to delete it I found it had all the code I needed and then it came to me that my SOURCE DIR WAS NAMED `Nexus` so I had to import Nexus not neux and I probably have to change the name because there is another damn lib named Nexus.

Thanks to all of you
I am sorry for wasting your time

**Comment by merwok** [comment]
OK!  To confirm, the distribution name (`pip install CoolProject`) is independent from the importable names (`import cool_project`).  A distribution can have 0 or more importable modules, 0 or more imporable packages, 0 or more scripts, etc.  The distribution name is set by the `name` parameter in `setup.py`, the imporable names depend on the file names (`example.py` → example, `nexus/__init__.py` → nexus).

Good that you found the problem!  You can close this ticket now.

**Comment by Saad-py** [comment]
What should I put in the setup.py so it installes some libraries that are used in the code and will allow me to get no error.

For example 
I have used numpy 
but my user doesn't has numpy so what should I put in the setup.py that it installs the libraries for the user if he doesn't has the libraries ??

**Comment by henryiii** [comment]
I have a guide with NumPy here: https://scikit-hep.org/developer/packaging. If you really prefer setup.py, it's the same thing there, `install_requires=["numpy>=1.13.3",],` or whatever you require.

**Comment by Saad-py** [comment]
Numpy was just an example @henryiii

Ok thanks

**Comment by henryiii** [comment]
> or whatever you require.

Yes, was just saying my examples were using NumPy too.
