### ISSUE TITLE
setuptools broke many popular python projects

### ISSUE THREAD

**Issue by alex** [pypa/packaging-problems#43]
setuptools made a backwards incompatible change (removing `setuptools.Feature`) which broke a bunch of packages (pymongo, cffi, markupsafe, etc.). Almost no users were aware this change was going to happen because deprecation warnings are silent by default. Further this change was made without actually checking to see if projects were using teh feature.

**Comment by ncoghlan** [comment]
Python 3.7+ makes DeprecationWarning visible by default in __main__ modules again, which will also make warnings visible in `setup.py` files.

`setuptools` may also want to consider using `FutureWarning` for some of its warnings (since those are always visible by default, regardless of Python version or the module that triggers them).
